# -*-Mode: makefile;-*-
# $Header: /Volumes/cvsrep/developer/OpenADFortTk/test/Makefile.old,v 1.2 2004/05/11 17:48:33 eraxxon Exp $

## * BeginCopyright *********************************************************
## *********************************************************** EndCopyright *

#############################################################################
# $Source: /Volumes/cvsrep/developer/OpenADFortTk/test/Makefile.old,v $
#############################################################################

#############################################################################
# Site/machine/architecture dependent configuration 
#############################################################################

include $(OPENADFORTTK)/test/Makeinclude.config

#############################################################################
# Site/machine/architecture independent configuration 
#############################################################################

all: build_tests run_tests

run   : run_tests
check : run_tests

.PHONY: all

#############################################################################

#-----------------------------------------------------------------
#  Build and Run Tests
#-----------------------------------------------------------------

TESTDIRS = lib/support

build_tests: 
	src=$(OPENADFORTTK)/test ; \
	for dir in $(TESTDIRS) ; do \
	  obj=$(OPENADFORTTK_OBJ_PATH)/test/$$dir ; \
	  mkdir -p $$obj ; \
	  cd $$obj ; \
	  $(MAKE) -f $$src/$$dir/Makefile SRCS=$$src/$$dir ; \
	done

# FIXME: It may be better to place test running in the respective
# directory (where it is built).
run_tests: 
	src=$(OPENADFORTTK)/test ; \
	for dir in $(TESTDIRS) ; do \
	  testdir=$(OPENADFORTTK_OBJ_PATH)/test/$$dir ; \
	  for test in `ls $$testdir/*.test` ; do \
	    $$test ; \
	  done \
	done

.PHONY: build_tests run_tests

#-----------------------------------------------------------------
#  Clean build files
#-----------------------------------------------------------------

clean: veryclean

veryclean:
	testdir=$(OPENADFORTTK_OBJ_PATH)/test ; \
	if [ -n "$(OPENADFORTTK_OBJ_PATH)" \
	     -a "$(OPENADFORTTK_OBJ_PATH)" != "/" ] ; then \
	  /bin/rm -f -r $${testdir}; \
	fi

.PHONY: clean veryclean


#-----------------------------------------------------------------
#  Vars
#-----------------------------------------------------------------

vars: 
	@echo CXX=$(CXX)
	@echo CC=$(CC)

.PHONY: vars
